---
# Aufgaben für Intrusion Prevention (Fail2ban)

- name: Fail2ban installieren
  apt:
    name: fail2ban
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Fail2ban lokale Jail-Konfiguration erstellen (jail.local)
  copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = {{ fail2ban_bantime }}
      findtime = {{ fail2ban_findtime }}
      maxretry = {{ fail2ban_maxretry }}

      [sshd]
      enabled = true
      port = {{ fail2ban_ssh_port }}
      logpath = %(sshd_log)s
      backend = %(sshd_backend)s
    owner: root
    group: root
    mode: '0644'
  notify: Restart Fail2ban

- name: Fail2ban Dienst aktivieren und starten
  service:
    name: fail2ban
    state: started
    enabled: yes