---
# Standard-Variablen für Kernel-Hardening (Sysctl)

# IP-Spoofing und Routing absichern
kernel_hardening_accept_source_route: 0
kernel_hardening_accept_redirects: 0
kernel_hardening_secure_redirects: 0
kernel_hardening_send_redirects: 0
kernel_hardening_rp_filter: 1

# Netzwerk-Attacken abwehren (SYN-Floods)
kernel_hardening_tcp_syncookies: 1

# Kernel-Logs schützen
kernel_hardening_dmesg_restrict: 1

# Core Dumps für suid-Prozesse deaktivieren
kernel_hardening_suid_dumpable: 0

# IPv6 deaktivieren (CIS 3.1.1)
kernel_hardening_disable_ipv6: false
