---
- name: Lokales Login-Banner (/etc/issue) konfigurieren (CIS 1.7.1.1)
  ansible.builtin.copy:
    content: "{{ login_banner_text }}"
    dest: /etc/issue
    owner: root
    group: root
    mode: '0644'

- name: Remote Login-Banner (/etc/issue.net) konfigurieren (CIS 1.7.1.2)
  ansible.builtin.copy:
    content: "{{ login_banner_text }}"
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
