---
# Standard-Variablen für das Patch-Management

# Eigene Variablen mit Präfix
patch_management_automatic_upgrades: 1
patch_management_origins_patterns:
  - "origin=Ubuntu,archive=${distro_codename}-security"
patch_management_unattended_mail: ""
patch_management_unattended_automatic_reboot: true
patch_management_unattended_automatic_reboot_time: "03:00"

# Damit die Tasks sie finden (Mapping):
unattended_automatic_upgrades: "{{ patch_management_automatic_upgrades }}"
unattended_package_list_update: 1
unattended_origins_patterns: "{{ patch_management_origins_patterns }}"
unattended_mail: "{{ patch_management_unattended_mail }}"
unattended_automatic_reboot: "{{ patch_management_unattended_automatic_reboot }}"
unattended_automatic_reboot_time: "{{ patch_management_unattended_automatic_reboot_time }}"
