---
- name: Lokales Login-Banner (/etc/issue) konfigurieren
  ansible.builtin.copy:
    content: "{{ login_banner_text }}"
    dest: /etc/issue
    owner: root
    group: root
    mode: '0644'

- name: Remote Login-Banner (/etc/issue.net) konfigurieren
  ansible.builtin.copy:
    content: "{{ login_banner_text }}"
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'

- name: SSH-Dienst anweisen, das Banner zu verwenden (/etc/ssh/sshd_config)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Banner "
    line: "Banner /etc/issue.net"
    state: present
  notify: Restart SSH
