---
# Aufgaben für Banner und Legal Notice

- name: SSH-Login-Warnbanner (/etc/issue.net) erstellen
  copy:
    dest: /etc/issue.net
    content: |
      =================================================================
      ACHTUNG: Unbefugter Zugriff auf dieses System ist strengstens verboten!
      Alle Aktivitäten werden überwacht und protokolliert.
      =================================================================
    owner: root
    group: root
    mode: '0644'

- name: Lokales Konsolen-Login-Banner (/etc/issue) erstellen
  copy:
    dest: /etc/issue
    content: |
      System Hardened by Ansible - Authorized Users Only\n\n
    owner: root
    group: root
    mode: '0644'

- name: SSH-Dienst anweisen, das Banner zu verwenden (/etc/ssh/sshd_config)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Banner '
    line: 'Banner /etc/issue.net'
    state: present
  notify: Restart SSH